import { Language } from './types';

export const SUPPORTED_LANGUAGES: { code: Language; label: string }[] = [
  { code: 'en', label: 'English' },
  { code: 'hi', label: 'हिंदी' },
  { code: 'bn', label: 'বাংলা' },
];

export const TRANSLATIONS = {
  en: {
    dashboard: 'Dashboard',
    clients: 'Clients',
    settings: 'Settings',
    totalProfit: 'Total Profit',
    totalReceived: 'Total Received',
    totalExpenses: 'Total Expenses',
    recentTransactions: 'Recent Transactions',
    addNewClient: 'Add New Client',
    clientName: 'Client Name',
    phone: 'Phone Number',
    address: 'Address',
    save: 'Save',
    cancel: 'Cancel',
    noClients: 'No clients found. Add one to get started!',
    addTransaction: 'Add Transaction',
    amountReceived: 'Amount Received',
    productCost: 'Product Cost',
    shippingCost: 'Shipping Cost',
    notes: 'Notes',
    date: 'Date',
    exportPdf: 'Export PDF',
    delete: 'Delete',
    viewDetails: 'View Details',
    darkMode: 'Dark Mode',
    language: 'Language',
    searchClients: 'Search clients...',
    profit: 'Profit',
    expense: 'Expense',
    revenue: 'Revenue',
    overview: 'Overview',
    thisMonth: 'This Month',
    allTime: 'All Time',
    invoice: 'Statement',
    grandTotal: 'Grand Total',
    generatedOn: 'Generated on',
    report: 'Report',
    quantity: 'Quantity',
    unitPrice: 'Unit Price',
    totalProductCost: 'Total Product Cost',
    editTransaction: 'Edit Transaction',
    update: 'Update'
  },
  hi: {
    dashboard: 'डैशबोर्ड',
    clients: 'ग्राहक',
    settings: 'सेटिंग्स',
    totalProfit: 'कुल लाभ',
    totalReceived: 'कुल प्राप्त',
    totalExpenses: 'कुल खर्च',
    recentTransactions: 'हाल के लेनदेन',
    addNewClient: 'नया ग्राहक जोड़ें',
    clientName: 'ग्राहक का नाम',
    phone: 'फ़ोन नंबर',
    address: 'पता',
    save: 'सहेजें',
    cancel: 'रद्द करें',
    noClients: 'कोई ग्राहक नहीं मिला। शुरू करने के लिए एक जोड़ें!',
    addTransaction: 'लेनदेन जोड़ें',
    amountReceived: 'प्राप्त राशि',
    productCost: 'उत्पाद लागत',
    shippingCost: 'शिपिंग लागत',
    notes: 'विवरण',
    date: 'दिनांक',
    exportPdf: 'PDF निर्यात करें',
    delete: 'हटाएं',
    viewDetails: 'विवरण देखें',
    darkMode: 'डार्क मोड',
    language: 'भाषा',
    searchClients: 'ग्राहक खोजें...',
    profit: 'लाभ',
    expense: 'खर्च',
    revenue: 'राजस्व',
    overview: 'अवलोकन',
    thisMonth: 'इस महीने',
    allTime: 'सभी समय',
    invoice: 'स्टेटमेंट',
    grandTotal: 'कुल योग',
    generatedOn: 'दिनांक',
    report: 'रिपोर्ट',
    quantity: 'मात्रा',
    unitPrice: 'इकाई मूल्य',
    totalProductCost: 'कुल उत्पाद लागत',
    editTransaction: 'लेनदेन संपादित करें',
    update: 'अपडेट करें'
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড',
    clients: 'ক্লায়েন্ট',
    settings: 'সেটিংস',
    totalProfit: 'মোট লাভ',
    totalReceived: 'মোট প্রাপ্তি',
    totalExpenses: 'মোট খরচ',
    recentTransactions: 'সাম্প্রতিক লেনদেন',
    addNewClient: 'নতুন ক্লায়েন্ট যোগ করুন',
    clientName: 'ক্লায়েন্টের নাম',
    phone: 'ফোন নম্বর',
    address: 'ঠিকানা',
    save: 'সংরক্ষণ',
    cancel: 'বাতিল',
    noClients: 'কোন ক্লায়েন্ট পাওয়া যায়নি। শুরু করতে একটি যোগ করুন!',
    addTransaction: 'লেনদেন যোগ করুন',
    amountReceived: 'প্রাপ্ত পরিমাণ',
    productCost: 'পণ্যের খরচ',
    shippingCost: 'শিপিং খরচ',
    notes: 'নোট',
    date: 'তারিখ',
    exportPdf: 'PDF ডাউনলোড',
    delete: 'মুছুন',
    viewDetails: 'বিস্তারিত দেখুন',
    darkMode: 'ডার্ক মোড',
    language: 'ভাষা',
    searchClients: 'ক্লায়েন্ট খুঁজুন...',
    profit: 'লাভ',
    expense: 'খরচ',
    revenue: 'আয়',
    overview: 'ওভারভিউ',
    thisMonth: 'এই মাস',
    allTime: 'সর্বকাল',
    invoice: 'বিবরণী',
    grandTotal: 'সর্বমোট',
    generatedOn: 'তারিখ',
    report: 'রিপোর্ট',
    quantity: 'পরিমাণ',
    unitPrice: 'একক মূল্য',
    totalProductCost: 'মোট পণ্য খরচ',
    editTransaction: 'লেনদেন সম্পাদনা',
    update: 'আপডেট'
  }
};